# TCL File Generated by Component Editor 23.1
# Tue Dec 10 17:42:53 MST 2024
# DO NOT MODIFY


# 
# LCD_Controller "LCD" v1.8
# Drew Currie 2024.12.10.17:42:53
# LCD Controller 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module LCD_Controller
# 
set_module_property DESCRIPTION "LCD Controller "
set_module_property NAME LCD_Controller
set_module_property VERSION 1.8
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Drew Currie"
set_module_property DISPLAY_NAME LCD
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL lcd_avalon_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file lcd_controller_avalon.vhd VHDL PATH ../../hdl/LCD-Controller/lcd_controller_avalon.vhd TOP_LEVEL_FILE
add_fileset_file lcd_controller.vhd VHDL PATH ../../hdl/LCD-Controller/lcd_controller.vhd
add_fileset_file clockDivider.vhd VHDL PATH ../../hdl/LCD-Controller/clockDivider.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point lcd_outputs
# 
add_interface lcd_outputs conduit end
set_interface_property lcd_outputs associatedClock clock
set_interface_property lcd_outputs associatedReset ""
set_interface_property lcd_outputs ENABLED true
set_interface_property lcd_outputs EXPORT_OF ""
set_interface_property lcd_outputs PORT_NAME_MAP ""
set_interface_property lcd_outputs CMSIS_SVD_VARIABLES ""
set_interface_property lcd_outputs SVD_ADDRESS_GROUP ""

add_interface_port lcd_outputs lcd_output readdata Output 10


# 
# connection point lcd_slave_1
# 
add_interface lcd_slave_1 avalon end
set_interface_property lcd_slave_1 addressUnits WORDS
set_interface_property lcd_slave_1 associatedClock clock
set_interface_property lcd_slave_1 associatedReset reset
set_interface_property lcd_slave_1 bitsPerSymbol 8
set_interface_property lcd_slave_1 burstOnBurstBoundariesOnly false
set_interface_property lcd_slave_1 burstcountUnits WORDS
set_interface_property lcd_slave_1 explicitAddressSpan 0
set_interface_property lcd_slave_1 holdTime 0
set_interface_property lcd_slave_1 linewrapBursts false
set_interface_property lcd_slave_1 maximumPendingReadTransactions 0
set_interface_property lcd_slave_1 maximumPendingWriteTransactions 0
set_interface_property lcd_slave_1 readLatency 0
set_interface_property lcd_slave_1 readWaitTime 1
set_interface_property lcd_slave_1 setupTime 0
set_interface_property lcd_slave_1 timingUnits Cycles
set_interface_property lcd_slave_1 writeWaitTime 0
set_interface_property lcd_slave_1 ENABLED true
set_interface_property lcd_slave_1 EXPORT_OF ""
set_interface_property lcd_slave_1 PORT_NAME_MAP ""
set_interface_property lcd_slave_1 CMSIS_SVD_VARIABLES ""
set_interface_property lcd_slave_1 SVD_ADDRESS_GROUP ""

add_interface_port lcd_slave_1 avs_read read Input 1
add_interface_port lcd_slave_1 avs_write write Input 1
add_interface_port lcd_slave_1 avs_address address Input 2
add_interface_port lcd_slave_1 avs_readdata readdata Output 32
add_interface_port lcd_slave_1 avs_writedata writedata Input 32
set_interface_assignment lcd_slave_1 embeddedsw.configuration.isFlash 0
set_interface_assignment lcd_slave_1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment lcd_slave_1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment lcd_slave_1 embeddedsw.configuration.isPrintableDevice 0

